projects:
  -
    name: Regolamento Foia
    short_name: foia
    description: "Regolamento sul diritto di accesso all'informazione e all'accesso ai documenti amministrativi."
    documents:
      - foia-regolamento-docs
  -
    name: Statuto Città Metropolitana di Napoli
    short_name: statuto cmna
    description: "Statuto della Città Metropolitana di Napoli."
    documents:
      - statuto-cmna-docs
  -
    name: Codice Comportamento Dipendenti
    short_name: cod comp
    description: "Codice di Comportamento dei Dipendenti della Città Metropolitana di Napoli."
    documents:
      - cod_comportamento_dipendenti-docs
  -
    name: Manuale Portale Utente - CRM
    short_name: CRM-Portal
    description: "Manuale d'uso interno del Portale Utente."
    documents:
      - portaleutente-manuale-docs
  -
    name: Contratto di Servizio - Portale Utente - CRM Vtiger
    short_name: SLA-Portal
    description: "Questo repository contiene il contratto di servizio SLA - Service Level Agreement."
    documents:
      - contratto-di-servizio-docs
