projects:
  - name: Documentazione Amministrativa
    short_name: italia-conf
    description: "Questo progetto consente la pubblicazione di documenti del comune di Palermo in stile docs-italia"
    documents:
      - docs-italia
      - comune di Palermo

