projects:
  -
    name: Regolamento Foia
    short_name: foia
    description: "Regolamento sul diritto di accesso all'informazione e all'accesso ai documenti amministrativi."
    documents:
      - foia-regolamento-docs
  -
    name: Statuto
    short_name: statuto
    description: Statuto
    documents:
      - statuto-docs
