projects:
  -
    name: Regolamento Foia
    short_name: foia
    description: "Regolamento sul diritto di accesso all'informazione e all'accesso ai documenti amministrativi."
    documents:
      - foia-regolamento-docs
  -
    name: Statuto Città Metropolitana di Napoli
    short_name: statuto cmna
    description: "Statuto della Città Metropolitana di Napoli."
    documents:
      - statuto-cmna-docs
  -
    name: Codice Comportamento Dipendenti
    short_name: cod comp
    description: "Codice di Comportamento dei Dipendenti della Città Metropolitana di Napoli."
    documents:
      - cod_comportamento_dipendenti-docs
 -
    name: Manuale Portale Utente CRM
    short_name: Man CRM
    description: "Manuale d'uso interno del Portale Utente - CRM vtiger per la gestione
    delle richieste di pubblicazione su sito istituzionale della Città Metropolitana di Napoli."
    documents:
      - portaleutente-manuale-docs
 -
    name: Contratto di Servizio - Portale Utente - CRM Vtiger
    short_name: Sla
    description: "Questo repository contiene il contratto di servizio SLA - Service Level Agreement, per i fruitori del servizio Portale Utente, basato su CRM vtiger. Il Portale Utente è un servizio ad uso esclusivo dei redattori interni, per la gestione delle richieste di pubblicazione sul sito istituzionale della Città Metropolitana di Napoli."
    documents:
      - contratto-di-servizio-docs
