publisher:
  name: "Comune di Palermo"
  short-name: "Comune di Palermo"
  description: "Ente di governo metropolitano"
  website: http://www.comune.palermo.it
  github_organization_url: github.com/ComuneDiPalermo
  tags:
    - documents
    - public
    - amazing publisher
  logo: assets/images/palermo.PNG
